version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: circleci/postgres:alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: npm install
workflows:
  version: 2
  build_and_test: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build
